openapi: 3.0.3

info:
  title: OpenAPI HttpFoundation Testing Laravel Example
  version: 1.0.0
  contact:
    name: Cristian Dumitriu
    url: http://localhost:8000/api

servers:
  - url: http://localhost:8000/api

paths:
  '/V1/events':
    get:
      responses:
        '200':
          description: Show paginated events collections
          content:
            application/json:
              schema:
                type: object
                required:
                 - data
                properties:
                  data:
                    type: array
                    items:
                      oneOf:
                        - $ref: '#/components/schemas/Event'

  '/V1/test':
    get:
      responses:
        '200':
          description: Test the api test endpoint
          content:
            application/json:
              schema:
                type: object
                required:
                  - foo
                properties:
                  foo:
                    type: string
                    example: bar

components:
  schemas:
    Event:
      type: object
      required:
        - id
      description: Model of an event
      properties:
        id:
          type: integer
          example: 54
        title:
          type: string
          example: some data for the title
        description:
          type: string
          example: Some long text for description

    Links:
      type: object
      description: Pagination links
      properties:
        first:
          type: string
          example: http://localhost/api/V1/events?page=1
        last:
          type: string
          example: http://localhost/api/V1/events?page=1
        prev:
          type: string
          example: http://localhost/api/V1/events?page=1
        next:
          type: string
          example: http://localhost/api/V1/events?page=1
